/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Ingrid
 */
public class Home extends javax.swing.JFrame {
    private float x, y;//Coordenadas del mouse.
    private final Color btn_normal = new Color(255,102,0);
    private final Color btn_hover = new Color(255,139,0);
    private final Color sep = new Color(204,204,204);

    private ImageIcon imageicon;//Icono para la aplicación.
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        imageicon = new ImageIcon(this.getClass().getResource("/images/005-documents.png"));//Icono para la app.
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        
//        jpanel_overlay.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        separador2 = new javax.swing.JLabel();
        separador1 = new javax.swing.JLabel();
        jpanel_overlay = new javax.swing.JPanel();
        lbl_mover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1086, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 56, 60));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(54, 56, 60));
        txt_username.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.setOpaque(false);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 360, 30));

        lbl_username.setBackground(new java.awt.Color(57, 113, 157));
        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(196, 80, 4));
        lbl_username.setText("Username");
        jPanel2.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lbl_password.setBackground(new java.awt.Color(57, 113, 157));
        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(196, 80, 4));
        lbl_password.setText("Password");
        jPanel2.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        txt_password.setBackground(new java.awt.Color(54, 56, 60));
        txt_password.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setBorder(null);
        txt_password.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_password.setOpaque(false);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 360, 30));

        btn_login.setBackground(new java.awt.Color(255, 102, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorderPainted(false);
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setFocusPainted(false);
        btn_login.setOpaque(true);
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 370, 40));

        btn_cerrar.setBackground(new java.awt.Color(54, 56, 60));
        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/002-cross-circular-button-outline-16x16.png"))); // NOI18N
        btn_cerrar.setToolTipText("Cerrar");
        btn_cerrar.setBorderPainted(false);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setFocusPainted(false);
        btn_cerrar.setOpaque(true);
        btn_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseExited(evt);
            }
        });
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 20, 20));

        separador2.setBackground(new java.awt.Color(204, 204, 204));
        separador2.setIconTextGap(1);
        separador2.setOpaque(true);
        jPanel2.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 370, 2));

        separador1.setBackground(new java.awt.Color(204, 204, 204));
        separador1.setIconTextGap(1);
        separador1.setOpaque(true);
        jPanel2.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 370, 2));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 560, 640));

        jpanel_overlay.setBackground(new java.awt.Color(255, 139, 0));
        jpanel_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpanel_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 640));

        lbl_mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_moverMouseDragged(evt);
            }
        });
        lbl_mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_moverMousePressed(evt);
            }
        });
        getContentPane().add(lbl_mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        btn_login.setBackground(btn_hover);
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setBackground(btn_normal);
    }//GEN-LAST:event_btn_loginMouseExited

    private void lbl_moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_moverMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lbl_moverMousePressed

    private void lbl_moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_moverMouseDragged
        this.setLocation(Math.round(this.getLocation().x + evt.getX() - x), Math.round(this.getLocation().y + evt.getY() - y));
    }//GEN-LAST:event_lbl_moverMouseDragged

    private void btn_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseEntered
        Image img = null;
        try {
            img = ImageIO.read(getClass().getResource("/images/001-cross-delete-black-circular-button16x16.png"));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_cerrar.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_btn_cerrarMouseEntered

    private void btn_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseExited
        Image img = null;
        try {
            img = ImageIO.read(getClass().getResource("/images/002-cross-circular-button-outline-16x16.png"));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_cerrar.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_btn_cerrarMouseExited

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        try {
            ConexionBD.Cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        separador1.setBackground(btn_normal);
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        separador1.setBackground(sep);
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        separador2.setBackground(btn_normal);
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        separador2.setBackground(sep);
    }//GEN-LAST:event_txt_passwordFocusLost

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String user = txt_username.getText();
        String pass = new String(txt_password.getPassword());
        
        if(user.isEmpty() || pass.isEmpty())
            generarAlerta("Debe colocar usuario y contraseña");
        else
        {
            if(ConexionBD.Conectar(user, pass))
            {
                new MainPanel().setVisible(true);
                this.dispose();

            }
            else
                generarAlerta("Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    public void generarAlerta(String mes)
    {
        JOptionPane.showMessageDialog(this, mes);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpanel_overlay;
    private javax.swing.JLabel lbl_mover;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel separador2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
